name = "website-test"
main = "src/index.js"
compatibility_date = "2024-01-01"

# For Node.js compatibility if needed
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "images-prod"